### ISSUE TITLE
[FEAT] Support for Java and Python

### ISSUE THREAD

**Issue by alphaX86** [Arch2x/codeit#12]
**Is your feature request related to a problem? Please describe.**
For now, CODEIt uses C++ as primary one. But I started to think if we need other languages too. IDK but if users (in future) request other lang support it must be prepared. 

**Describe the solution you'd like**
If support for one lang is to be made, it must have two kinds of templates. One is simple and other is for aggressive coders. 

**Describe alternatives you've considered**
No alternative is imposed but feel free to discuss about this one.

**Comment by Sudip704** [comment]
I would like to work on this issue, can u please say what to do and how to do it.

**Comment by Sudip704** [comment]
I would like to work on this issue. Could you please assign me this issue.

**Comment by alphaX86** [comment]
> I would like to work on this issue. Could you please assign me this issue.

Copy that!

**Comment by alphaX86** [comment]
Your time starts now! Deadline: 1 day

**Comment by Sudip704** [comment]
sorry dada I have a test tomorrow, I came to know now, I want to start my work from monday-tuesday

**Comment by Sudip704** [comment]
please dada, can you give me the chance to fix the issue later, not now

**Comment by alphaX86** [comment]
You mean from Monday or Tuesday? In such case, someone may come and ask. Hmm, IDK but if no one comes to take it until that time, I'll assign you @Sudip704. I'm doing this according to the rules specified.
