### ISSUE TITLE
[FEAT] Add 3rd function to implement files without TXT files

### ISSUE THREAD

**Issue by alphaX86** [Arch2x/codeit#21]
**Is your feature request related to a problem? Please describe.**
So far, CODEIt creates C++ files and TXT files to create directories. But what if user needs to implement files without those files?! 

**Describe the solution you'd like**
I need a function or an option TBH where user can implement files without TXT files. This requires a function and needs a proper help. In such case, I'll assign this as a easy issue. It's easy as you may need to refer a function and implement straight. 

**Describe alternatives you've considered**
None

**Additional context**
If support is needed, I'll help on this one. I'll guide where to add such options and all. If you're interested, tag me using @ symbol. And my username is alphaX86

**Comment by codeit13** [comment]
@alphaX86 I don't understand what this issue is. I did go through the code and I found out that directories in '-i' switch were created using `os.makedirs(os.path.join(os.getcwd(), contestName))` But in the description, you said that it depends on TXT files to create directories. Can you explain it more clearly to me?
I want to contribute to this issue.

**Comment by alphaX86** [comment]
OK, seems you're confused 😅.

So far, I used functions where when user gives a request to create a contest directory, it creates C++ files and TXT files (input.txt, output.txt) But I started to think that a user may not need such text files all time. So, that's why I need a function where it creates C++ files alone.

If you have more doubts or struck on this, ping me again @codeit13

**Comment by codeit13** [comment]
Ok, So you need a function like `codeit -only-files` which will create only the 6 cpp files in the current folder user is in.

Can you also suggest something instead of `codeit -only-files`

**Comment by alphaX86** [comment]
@codeit13 Well, the name part is yours! Some suggestions include `codeit -nT` or `codeit -NT` for command request. (Always keep the flags short for easy typing, but it's your call) Ok, so for this issue, you need to work on these files
 - `codeit.py`
 - `codeitInit.py`
 - `codeitHelp.py` (after making changes)
 
 This is the change I expect. If you're struck, please let me know. And yep, it's easy

**Comment by alphaX86** [comment]
BTW answer this Q alone, are you contributing this repo as a [JWoC](https://jwoc2k20.tech/) participant? If no, you can ignore this question and start your work.

**Comment by codeit13** [comment]
Yes I am a JWOC Participant
Discord Username: @astropsumit
